# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alexander Greenberg
email: alexander.greenberg@lmh.ox.ac.uk
description: >
  Alexander Greenberg | Philosophy
url: "http://alexandergreenberg.github.io" # the base hostname & protocol for your site
twitter_username: alexandergreenberg
github_username: alexandergreenberg
academia_username: alexandergreenberg

# Build settings
sass:
  sass-dir: _sass
include: ['_pages']
markdown: kramdown
